- name: Installing MariaDB Server and the Client...
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Enabling MariaDB Service and Starting it...
  service:
    name: mariadb
    enabled: yes
    state: started
 
# - name: Copying .my.cnf to the $HOME Directory...
#   template: 
#     src: my.cnf.j2
#     dest: /root/.my.cnf
#

