---
- name: Copying Repository Configurations...
  copy: 
    src: "{{ item }}"
    dest: /etc/yum.repos.d/ 
  with_items: 
      - epel.repo
      - MariaDB.repo
      - webtatic.repo
      - docker-ce.repo
      - nodesource-el7.repo

- name: Copying Repository GPG Signing Keys...
  copy: 
    src: "{{ item }}"
    dest: /etc/pki/rpm-gpg/
  with_items: 
      - keys/RPM-GPG-KEY-EPEL-7
      - keys/RPM-GPG-KEY-webtatic-el7
      - keys/NODESOURCE-GPG-SIGNING-KEY-EL


